TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := false
TARGET_NO_RECOVERY := false
TARGET_RECOVERY_FSTAB := device/generic/qemu/shared/fstab.qemu
TARGET_FLATTEN_APEX := false

#
# mkbootimg args
#

TARGET_PREBUILT_KERNEL := device/generic/qemu/prebuilts/$(TARGET_ARCH)/android16-6.13.img
BOARD_IMG_USE_RAMDISK := true
BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
BOARD_MOVE_GSI_AVB_KEYS_TO_VENDOR_BOOT := true

BOARD_BOOT_HEADER_VERSION := 4
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)

BOARD_INIT_BOOT_HEADER_VERSION := 4
BOARD_MKBOOTIMG_INIT_ARGS += --header_version $(BOARD_INIT_BOOT_HEADER_VERSION)

TARGET_USERIMAGES_SPARSE_EXT_DISABLED := true

#
# Device tree
#

BOARD_USES_DT := true
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_PREBUILT_DTBIMAGE_DIR := $(PRODUCT_OUT)/dtbs
BOARD_PREBUILT_DTBIMAGE := $(PRODUCT_OUT)/$(TARGET_DEVICE)_dtb.img

#
# kernel cmdline options
#

BOARD_KERNEL_CMDLINE += init=/init
BOARD_KERNEL_CMDLINE += printk.devkmsg=on

#
# Bootconfig
#

BOARD_BOOTCONFIG += androidboot.selinux=permissive
BOARD_BOOTCONFIG += androidboot.fstab_suffix=qemu
BOARD_BOOTCONFIG += androidboot.hardware=qemu

#
# Android Verified Boot (AVB)
#

BOARD_AVB_ENABLE := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x04000000
BOARD_INIT_BOOT_IMAGE_PARTITION_SIZE := 0x800000
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 0x04000000
BOARD_DTBIMG_PARTITION_SIZE := 0x01000000

#
# Recovery
#

TARGET_RECOVERY_UI_LIB := librecovery_ui_qemu

AB_OTA_UPDATER := true

AB_OTA_PARTITIONS += \
    boot \
    init_boot \
    vendor_boot \
    system \
    vendor \
    vbmeta \
    vbmeta_system \
    vbmeta_vendor \

BOARD_SUPER_PARTITION_SIZE := 8531214336
BOARD_SUPER_PARTITION_GROUPS := qemu_dynamic_partitions
BOARD_QEMU_DYNAMIC_PARTITIONS_SIZE := 8527020032

BOARD_QEMU_DYNAMIC_PARTITIONS_PARTITION_LIST := \
    system \
    vendor \
#
# Enable chained vbmeta for system images
#

BOARD_AVB_VBMETA_SYSTEM := system
BOARD_AVB_VBMETA_SYSTEM_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VBMETA_SYSTEM_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX_LOCATION := 1

#
# system image
#
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4


# Enable chained vbmeta for boot images
BOARD_AVB_BOOT_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_BOOT_ALGORITHM := SHA256_RSA2048
BOARD_AVB_BOOT_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_BOOT_ROLLBACK_INDEX_LOCATION := 2

BOARD_BOOTIMAGE_PARTITION_SIZE := 0x04000000

#
# Enable chained vbmeta for vendor images
#

BOARD_AVB_VBMETA_VENDOR := vendor
BOARD_AVB_VBMETA_VENDOR_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VBMETA_VENDOR_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX_LOCATION := 3

#
# Enable chained vbmeta for init_boot images
#

BOARD_AVB_INIT_BOOT_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_INIT_BOOT_ALGORITHM := SHA256_RSA2048
BOARD_AVB_INIT_BOOT_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_INIT_BOOT_ROLLBACK_INDEX_LOCATION := 4

#
# vendor image
#

BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor

#
# userdata image
#

BOARD_USERDATAIMAGE_PARTITION_SIZE := 536870912
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4

#
# super image
#

BOARD_BUILD_SUPER_IMAGE := true
BOARD_BUILD_SUPER_IMAGE_BY_DEFAULT := true
BOARD_SUPER_PARTITION_METADATA_DEVICE := super
